// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofwzghbkdspmjeakmuml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9md3pnaGJrZHNwbWplYWttdW1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMjMzNjQsImV4cCI6MjA2MTY5OTM2NH0.CABh0Ig6uO2NG3wpvRYfeg-aU59BeZ7w5qawQCom8aQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);